services:
  marceen_kontakt.controller.kontakt:
    class: Marceen\KontaktBundle\Controller\KontaktController
    arguments: [@command_bus]
    calls:
      - [setContainer, [@service_container]]
      - [setUnitOfWork, [@unit_of_work]]

  marceen_kontakt.form.type.kontakt:
    class: Marceen\KontaktBundle\Form\Type\KontaktType
    tags: [{ name: form.type, alias: kontakt }]

  marceen_kontakt.repository.kontakt:
    class: Marceen\KontaktBundle\Repository\Doctrine\KontaktRepository
    arguments: [@doctrine.orm.entity_manager]

  marceen_kontakt.handler.mail.dodaj:
    class: Marceen\KontaktBundle\CommandBus\Mail\DodajMailHandler
    arguments: [@marceen_kontakt.repository.kontakt, @event_dispatcher]
    tags: [{ name: command_handler, handles: Marceen\KontaktBundle\CommandBus\Mail\DodajMail }]

  marceen_kontakt.listener.mail.wysylka:
    class: Marceen\KontaktBundle\EventListener\WysylkaMailaListener
    arguments: [@component.mail]
    tags:
      - { name: kernel.event_listener, event: marceen.mail.add, method: onDodanoMail }
      - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
